### ISSUE TITLE
No module named 'config_parser'

### ISSUE THREAD

**Issue by silverwind** [lebinh/ngxtop#33]
Installed on ARM (Arch) and got this error. Could it be Python 3 related?

``` bash
$ ngxtop
Traceback (most recent call last):
  File "/usr/bin/ngxtop", line 7, in <module>
    from ngxtop.ngxtop import main
  File "/usr/lib/python3.4/site-packages/ngxtop/ngxtop.py", line 77, in <module>
    from config_parser import detect_log_config, detect_config_path, extract_variables, build_pattern
ImportError: No module named 'config_parser'
```

``` bash
$ python -V
Python 3.4.0
```

``` bash
$ python2 -V
Python 2.7.6
```

**Comment by j2ghz** [comment]
Encountered today:
```
# pip3 show ngxtop
Name: ngxtop
Version: 0.0.2
Summary: Real-time metrics for nginx server
Home-page: https://github.com/lebinh/ngxtop
Author: Binh Le
Author-email: lebinh.it@gmail.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: tabulate, pyparsing, docopt

# python3 -V
Python 3.5.2+

# ngxtop
Traceback (most recent call last):
  File "/usr/local/bin/ngxtop", line 7, in <module>
    from ngxtop.ngxtop import main
  File "/usr/local/lib/python3.5/dist-packages/ngxtop/ngxtop.py", line 77, in <module>
    from config_parser import detect_log_config, detect_config_path, extract_variables, build_pattern
ImportError: No module named 'config_parser'
```
Using python2 works
