### ISSUE TITLE
Wrong if syntax

### ISSUE THREAD

**Issue by michael-xiii** [lebinh/ngxtop#46]
Hello!
```
[michael_xiii@new-host ~]$ sudo /usr/bin/pip-python install ngxtop
Downloading/unpacking ngxtop
  Downloading ngxtop-0.0.2.tar.gz
  Running setup.py egg_info for package ngxtop
Downloading/unpacking docopt (from ngxtop)
  Downloading docopt-0.6.2.tar.gz
  Running setup.py egg_info for package docopt
    Traceback (most recent call last):
      File "<string>", line 14, in ?
      File "/home/michael_xiii/build/docopt/setup.py", line 3, in ?
        from docopt import __version__
      File "docopt.py", line 49
        uniq = list(set(self.flat())) if uniq is None else uniq
                                                ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in ?

  File "/home/michael_xiii/build/docopt/setup.py", line 3, in ?

    from docopt import __version__

  File "docopt.py", line 49

    uniq = list(set(self.flat())) if uniq is None else uniq

                                            ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1

```

Python 2.4.3 (#1, Jan  9 2013, 06:47:03) 

#uname -a
Linux XXX 2.6.18-238.19.1.el5.028stab092.2 #1 SMP Thu Jul 21 19:23:22 MSD 2011 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lebinh** [comment]
Hi, this is because the `docopt` library used to parse command line arguments doesn't support python 2.4. You will need at least Python 2.6 to run `ngxtop`. Also, look like you are using RHEL or CentOS 5 so maybe you can use the [EPEL](https://fedoraproject.org/wiki/EPEL) repo to install Python 2.6 first and reinstall `ngxtop` for it.
