### ISSUE TITLE
ImportError: No module named 'config_parser' under python 3.4

### ISSUE THREAD

**Issue by cloudtrends** [lebinh/ngxtop#49]
I run ngxtop in virtualenv: can not find config_parser 

(py3virtualenv)[root@xxxx ~]# ngxtop
Traceback (most recent call last):
  File "/root/py3virtualenv/bin/ngxtop", line 7, in <module>
    from ngxtop.ngxtop import main
  File "/root/py3virtualenv/lib/python3.4/site-packages/ngxtop/ngxtop.py", line 77, in <module>
    from config_parser import detect_log_config, detect_config_path, extract_variables, build_pattern
ImportError: No module named 'config_parser'

**Comment by djmattyg007** [comment]
This has already been fixed. It would be great if we could get another official release so it can be packaged.

**Comment by Yamakaky** [comment]
all internal modules like `utils` or `config_parser` need to be prefixed by `ngxtop.`, like in `from ngxtop.utils import ...`

**Comment by bitnumus** [comment]
Still not fixed in pip package?

**Comment by mgrijalva** [comment]
For anyone who has come across this (like me), you can clone the git repo and install it from that if you need to get going:

```
git clone https://github.com/lebinh/ngxtop
cd ngxtop
pip install .
```
