### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by devsmart** [lebinh/ngxtop#63]
Not able to install. appreciate help.
[pip.log.zip](https://github.com/lebinh/ngxtop/files/222736/pip.log.zip)

```
Downloading/unpacking ngxtop
  Downloading ngxtop-0.0.2-py2.py3-none-any.whl
Downloading/unpacking pyparsing (from ngxtop)
  Downloading pyparsing-2.1.1-py2.py3-none-any.whl
Downloading/unpacking docopt (from ngxtop)
  Downloading docopt-0.6.2.tar.gz
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 643, in unpack_file
    untar_file(filename, location)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 551, in untar_file
    os.makedirs(location)
  File "/usr/lib/python2.7/os.py", line 157, in makers
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/tmp/pip_build_root/docopt'

Storing debug log for failure in /root/.pip/pip.log

```

**Comment by meftaul** [comment]
I also facing same problem.
